# put your global settings header
header = "Jack in a Box"
footer = "an Arduino powerd prottyping framework"
slide_numbering = true
# if you  specify something for your slides it will overwrite the
# global settings. Make sure you always add the index of your slide
# starting at 1 to tell frontal which slide to set
# [[slides]]
# index = 3
# header = "header slide 3 overwrite with foo"
# footer = "footer slide 3 bah"
# [[slides]]
# index = 6
# header = "6 baz"
# footer = "6 something"
